# Generated by Django 5.0.2 on 2024-10-27 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassHubApp', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
